//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Cust_FName { get; set; }
        public string Cust_LName { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_Tel { get; set; }
        public string Cust_Address { get; set; }
    }
}
